#pragma once

#include <iostream>
#include <JuceHeader.h>
#include "Beat.h"

// This class is in charge of generating the audio corresponding to a given rhythm and processing any incoming audio to detect claps.
class RhythmProcessor : public juce::AudioProcessor
{
public:
  RhythmProcessor();
  ~RhythmProcessor();
  // Sets all boradcasters used by the rhythm processor to send signals to the MainComponent's signal listeners
  void setBroadcaster(juce::ChangeBroadcaster *roundBroadcaster, juce::ChangeBroadcaster *onBeatBroadcaster, juce::ChangeBroadcaster *loseBroadcaster, juce::ChangeBroadcaster *offBeatBroadcaster, juce::ChangeBroadcaster *clapBroadcaster);
  // Generates the output audio samples for a rhythm based off of the beat parameters generated by the MetrenomeComponent
  // in newRhythm(). After creating the audio samples, sets the RhythmProcessor's isPlaying flag to true to start
  // processing the game audio
  void generateRhythm(Beat *beats, int totalBeats, float secPerBeat);
  // Initializes RhythmProcessor settings based off of user input, retieved from the MainComponent
  void updateSettings(float sensitivity, bool debug);
  // Loads filter coeffecients from a resource text file into a vector of floats. If at any point an
  // error occures while parsing the text file, all values are cleared from the vector, so no filtering will occur
  void loadFilterCoeffs();
  void prepareToPlay(double sampleRate, int maximumExpectedSamplesPerBlock) override;
  void releaseResources() override;
  // Process any input audio loaded in the audio buffer, then fills the audio buffer with generated output samples.
  // It is important to note that this function is ran on a seperate thread to the rest of the program, but sends signals the MainComponent
  // class to keep track of on/off-beats and to indicate a game loss
  void processBlock(juce::AudioBuffer<float> &buffer, juce::MidiBuffer &midiMessages) override;
  const juce::String getName() const override;
  virtual double getTailLengthSeconds() const override;
  bool acceptsMidi() const override;
  bool producesMidi() const override;
  juce::AudioProcessorEditor *createEditor() override;
  bool hasEditor() const override;
  int getNumPrograms() override;
  int getCurrentProgram() override;
  void setCurrentProgram(int index) override;
  const juce::String getProgramName(int index) override;
  void changeProgramName(int index, const juce::String &newName) override;
  void getStateInformation(juce::MemoryBlock &destData) override;
  void setStateInformation(const void *data, int sizeInBytes) override;

private:
  juce::ChangeBroadcaster *roundBroadcaster;
  juce::ChangeBroadcaster *onBeatBroadcaster;
  juce::ChangeBroadcaster *loseBroadcaster;
  juce::ChangeBroadcaster *offBeatBroadcaster;
  juce::ChangeBroadcaster *clapBroadcaster;
  std::list<float> sampleWindow;
  std::vector<float> filterCoeffs;
  Beat *beats;
  bool isPlaying;
  bool isProcessing;
  bool debug;
  int currentSample;
  int totalSamples;
  int samplesPerBeat;
  int currentBeat;
  int totalBeats;
  int missedBeats;
  int roundCount;
  int windowSize;
  int soundDuration;
  int clapCount;
  int minDuration;
  int maxDuration;
  int coeffNum;
  float threshold;
  float toneDuration;
  float currentSampleRate;
  float frequencies[5];
  float *samples;

  JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(RhythmProcessor)
};
